 -- 01_BRONZE.SQL
-- Bronze Layer Implementation
-- Source: SNOWFLAKE_SAMPLE_DATA.TPCH_SF1
-- Project: modern-retail-analytics
 
-- 1️⃣ CREATE DATABASE & SCHEMA

CREATE OR REPLACE DATABASE RETAIL_WAREHOUSE;

USE DATABASE RETAIL_WAREHOUSE;

CREATE OR REPLACE SCHEMA BRONZE_LAYER;

USE SCHEMA BRONZE_LAYER;

-- 2️⃣ COPY TPCH TABLES INTO BRONZE
 
-- CUSTOMER
CREATE OR REPLACE TABLE CUSTOMER AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER;

-- ORDERS
CREATE OR REPLACE TABLE ORDERS AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS;

-- LINEITEM
CREATE OR REPLACE TABLE LINEITEM AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM;

-- PART (Product)
CREATE OR REPLACE TABLE PART AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART;

-- SUPPLIER
CREATE OR REPLACE TABLE SUPPLIER AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER;

-- NATION
CREATE OR REPLACE TABLE NATION AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION;

-- REGION
CREATE OR REPLACE TABLE REGION AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION;
 
-- 3️⃣ VALIDATE ROW COUNTS (SOURCE VS BRONZE)
 
SELECT 'CUSTOMER' AS TABLE_NAME,
       (SELECT COUNT(*) FROM BRONZE_LAYER.CUSTOMER) AS BRONZE_COUNT,
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER) AS SOURCE_COUNT
UNION ALL
SELECT 'ORDERS',
       (SELECT COUNT(*) FROM BRONZE_LAYER.ORDERS),
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS)
UNION ALL
SELECT 'LINEITEM',
       (SELECT COUNT(*) FROM BRONZE_LAYER.LINEITEM),
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM)
UNION ALL
SELECT 'PART',
       (SELECT COUNT(*) FROM BRONZE_LAYER.PART),
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART)
UNION ALL
SELECT 'SUPPLIER',
       (SELECT COUNT(*) FROM BRONZE_LAYER.SUPPLIER),
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER)
UNION ALL
SELECT 'NATION',
       (SELECT COUNT(*) FROM BRONZE_LAYER.NATION),
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION)
UNION ALL
SELECT 'REGION',
       (SELECT COUNT(*) FROM BRONZE_LAYER.REGION),
       (SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION);

SELECT * FROM BRONZE_LAYER.CUSTOMER LIMIT 5;
SELECT * FROM BRONZE_LAYER.ORDERS LIMIT 5;

